# Feature Engineering

This notebook creates the input features used by the predictive model.

These features are designed for forecasting rather than for descriptive EDA.
In particular, each feature row should use only information that would have been available before the target draw, so the current draw does not leak directly into the feature values.

### 1. Library Imports

In [1]:
import sys
from pathlib import Path

sys.path.append(str(Path.cwd().resolve().parent))

import pandas as pd

from src.features.build_features import build_feature_dataset
from src.config import FEATURE_LOTTO_FILE

### 2. Build the Feature Set

The current feature set is built from two components:

- Number-specific appearance frequency over the most recent `window` draws
- Gap features measuring how many draws have passed since each number last appeared

The resulting dataset will be used as the model input in the baseline notebook.

In [2]:
feature_df = build_feature_dataset()

feature_df.head()

,freq_1,freq_2,freq_3,freq_4,freq_5,freq_6,freq_7,freq_8,freq_9,freq_10,...,gap_36,gap_37,gap_38,gap_39,gap_40,gap_41,gap_42,gap_43,gap_44,gap_45
0,1.0,4.0,3.0,3.0,0.0,3.0,2.0,1.0,4.0,2.0,...,10.0,4.0,2.0,2.0,2.0,10.0,8.0,2.0,11.0,9.0
1,1.0,4.0,3.0,3.0,0.0,4.0,2.0,1.0,4.0,1.0,...,11.0,5.0,3.0,3.0,3.0,11.0,9.0,3.0,12.0,10.0
2,1.0,4.0,3.0,4.0,1.0,5.0,2.0,2.0,3.0,1.0,...,12.0,6.0,4.0,1.0,4.0,12.0,10.0,4.0,13.0,11.0
3,1.0,4.0,3.0,4.0,2.0,5.0,2.0,2.0,3.0,1.0,...,13.0,7.0,5.0,2.0,5.0,13.0,1.0,5.0,14.0,12.0
4,1.0,4.0,3.0,4.0,2.0,5.0,3.0,3.0,3.0,1.0,...,1.0,8.0,6.0,3.0,6.0,14.0,2.0,1.0,15.0,13.0

In [3]:
feature_df.shape

(1194, 90)

In [4]:
df_features = pd.read_csv(FEATURE_LOTTO_FILE)

df_features.head()

,freq_1,freq_2,freq_3,freq_4,freq_5,freq_6,freq_7,freq_8,freq_9,freq_10,...,gap_36,gap_37,gap_38,gap_39,gap_40,gap_41,gap_42,gap_43,gap_44,gap_45
0,1.0,4.0,3.0,3.0,0.0,3.0,2.0,1.0,4.0,2.0,...,10.0,4.0,2.0,2.0,2.0,10.0,8.0,2.0,11.0,9.0
1,1.0,4.0,3.0,3.0,0.0,4.0,2.0,1.0,4.0,1.0,...,11.0,5.0,3.0,3.0,3.0,11.0,9.0,3.0,12.0,10.0
2,1.0,4.0,3.0,4.0,1.0,5.0,2.0,2.0,3.0,1.0,...,12.0,6.0,4.0,1.0,4.0,12.0,10.0,4.0,13.0,11.0
3,1.0,4.0,3.0,4.0,2.0,5.0,2.0,2.0,3.0,1.0,...,13.0,7.0,5.0,2.0,5.0,13.0,1.0,5.0,14.0,12.0
4,1.0,4.0,3.0,4.0,2.0,5.0,3.0,3.0,3.0,1.0,...,1.0,8.0,6.0,3.0,6.0,14.0,2.0,1.0,15.0,13.0

### 3. Summary

This notebook builds a forecasting-oriented feature table from the cleaned lotto history.

The final dataset combines rolling frequency features and gap features, and each row is structured so that it uses only information available before the target draw. This feature table is the direct input to the baseline model notebook.